# Generated by Django 6.0.3 on 2026-03-11 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0003_buscadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='buscadores',
            old_name='apellido',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='buscadores',
            old_name='nombre',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='buscadores',
            name='email',
        ),
        migrations.AlterField(
            model_name='buscadores',
            name='profesion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=5000)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('D', 'Draft'), ('P', 'Posted')], default='D', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
