# Generated by Django 6.0.3 on 2026-03-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0004_type_rename_apellido_buscadores_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('PD', 'Predatory'), ('BV', 'Benevolent'), ('AQ', 'Aquatic'), ('U', 'Undefined')], default='U', max_length=2),
        ),
    ]
