# Generated by Django 6.0.3 on 2026-03-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
