# Generated by Django 6.0.3 on 2026-03-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='user',
        ),
    ]
